// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://lhoogddkugjqagayegmr.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imxob29nZGRrdWdqcWFnYXllZ21yIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTAzMTM1MzgsImV4cCI6MjA2NTg4OTUzOH0.Xf9kLkqVkEzEwCEyZOUPjvDUhKJsXVVSwVIE-1YYiLs";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);